### ISSUE TITLE
Batt not visible in Traccar

### ISSUE THREAD

**Issue by sincze** [lorenzo-deluca/homeassistant-traccar#2]
This works great, unfortunately my Batt status is not populated to traccar
It remains at 0% however the data is available in Homeassistant.

Anything I missed ??

**Comment by lorenzo-deluca** [comment]
Check if the battery level on Homeassistant device is in attribute called "battery_level".
If is not you have to change the package automation on like
````yaml
        batt: '{{ state_attr(trigger.entity_id, ''battery_level'') | float(0) }}'

**Comment by sincze** [comment]
device_tracker devices (device_tracker.telefoon1) that I need to add to the yaml have the following attributes

Source  GPS
Latitude 10,12
Longitude 3,22
GPS accuracy 11
Altitude 47
Course 0
Speed 0
Vertical accuracy 1

No battery value that is located in the sensor.telefoon1_battery_level.

**Comment by lorenzo-deluca** [comment]
So this is why you don't see battery on Traccar ... for example my iOS App have this values:

````yaml
source_type: gps
battery_level: 90
latitude: xxx
longitude: yyyy
gps_accuracy: 8
altitude: 240.3122673034668
vertical_accuracy: 27
friendly_name: iPhone Lorenzo
````
If you have battery on another entity you can edit the automation on the line that I've mention before, BUT it works ONLY for this device..!
So if you want to track more devices you've to duplicate several time this automation... not the best way but works.
