### ISSUE TITLE
Traccar_positionning.yaml update

### ISSUE THREAD

**Issue by Nothinx44** [lorenzo-deluca/homeassistant-traccar#6]
Hi, 
The Traccar_positionning.yaml have to be updated : 

Old :
 trigger:
    - platform: state
  action:
    - service:
    - 
Have to be like that's : 
New : 

 triggers:
      - trigger: state
  actions:
      - action: rest_command.update_traccar

**Comment by lorenzo-deluca** [comment]
You're right, fixed ;)

**Comment by razorman8669** [comment]
@lorenzo-deluca I think you need to make a few more updates for this to work (it's currently throwing errors in the automation).  here's my yaml
```
rest_command:
  update_traccar:
    url: "http://a0d7b954-traccar:5055" # if using Home Assistant Traccar Add-on
    method: GET
    payload: "?id={{id}}&lat={{lat}}&lon={{lon}}&altitude={{alt}}&batt={{batt}}&speed={{speed}}"

automation:
  - id: "position_tracking_update_traccar_position"
    alias: Position - Update Traccar Position
    triggers:
      - trigger: state
        entity_id: device_tracker.<YOUR_TRACKER_ID>
    conditions:
      - condition: template
        value_template: "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"
      - condition: template
        value_template: "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
    actions:
      - action: rest_command.update_traccar
        continue_on_error: true
        data:
          id: "{{ trigger.entity_id }}"
          lat: "{{ state_attr(trigger.entity_id, 'latitude')  | float(0) }}"
          lon: "{{ state_attr(trigger.entity_id, 'longitude') | float(0) }}"
          alt: "{{ state_attr(trigger.entity_id, 'altitude') | float(0) }}"
          batt: >
            {% set device_tracker = trigger.entity_id %}
            {% set battery_level = state_attr(device_tracker, 'battery_level') %}
            {% if battery_level is not none %}
              {{ battery_level | float(0) }}
            {% else %}
              {% set battery_sensor_id = 'sensor.' ~ device_tracker.split('.')[1] ~ '_battery_level' %}
              {% if states(battery_sensor_id) is not none %}
                {{ states(battery_sensor_id) | float(0) }}
              {% else %}
                0
              {% endif %}
            {% endif %}
          speed: "0"
    mode: parallel
    max: 10
```
